services:
  cf-warp:
    image: ghcr.io/roydvs/docker-cloudflare-warp:latest
    build: .
    restart: unless-stopped
    networks:
      - cf-warp
    environment:
      - WARP_MODE=${WARP_MODE:-warp}
      - WARP_PROTOCOL=${WARP_PROTOCOL:-masque}
      - WARP_LICENSE=${WARP_LICENSE:-}
      - WARP_ORG=${WARP_ORG:-}
      - WARP_CLIENT_ID=${WARP_CLIENT_ID:-}
      - WARP_CLIENT_SECRET=${WARP_CLIENT_SECRET:-}
    volumes:
      - warp-config-warp:/var/lib/cloudflare-warp
    healthcheck:
      test: ["CMD", "curl", "https://www.cloudflare.com/cdn-cgi/trace", "-fsS"]
      interval: 30s
      timeout: 10s
      retries: 3
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun

  cf-warp-proxy:
    image: ghcr.io/roydvs/docker-cloudflare-warp:latest
    build: .
    restart: unless-stopped
    networks:
      - cf-warp
    environment:
      - WARP_MODE=${WARP_MODE:-proxy}
      - WARP_PROXY_PORT=${WARP_PROXY_PORT:-40000}
      - WARP_PROTOCOL=${WARP_PROTOCOL:-masque}
      - WARP_LICENSE=${WARP_LICENSE:-}
      - WARP_ORG=${WARP_ORG:-}
      - WARP_CLIENT_ID=${WARP_CLIENT_ID:-}
      - WARP_CLIENT_SECRET=${WARP_CLIENT_SECRET:-}
    volumes:
      - warp-config-proxy:/var/lib/cloudflare-warp
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-x",
          "socks5h://127.0.0.1:${WARP_PROXY_PORT:-40000}",
          "https://www.cloudflare.com/cdn-cgi/trace",
          "-fsS",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    ports:
      - "40000:${WARP_PROXY_PORT:-40000}"

volumes:
  warp-config-warp:
    driver: local
  warp-config-proxy:
    driver: local

networks:
  cf-warp:
    driver: bridge
